name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    #container: 
    #  image: envoyproxy/envoy-build:latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: |
        wget https://raw.githubusercontent.com/envoyproxy/envoy-build-tools/master/build_container/build_container_common.sh
        wget https://raw.githubusercontent.com/envoyproxy/envoy-build-tools/master/build_container/build_container_ubuntu.sh
        bash build_container_ubuntu.sh
    - name: build
      run: ./ci/do_ci.sh build

