name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    #container: 
    #  image: envoyproxy/envoy-build:latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build
      run: ./ci/do_ci.sh build

